name: Build the docs

on:
  pull_request:
    branches:
      - main
      - docs

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install .[optimization,cheminfo,docs]
      - name: Create softlinks for notebooks
        run: ln -s tutorials/getting_started.ipynb docs/getting_started.ipynb
      - name: Build docs
        run: mkdocs build
