name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Minimal Bofire
        run: pip install "."
      - name: Run domain-only test
        run: pytest tests/bofire/data_models/test_domain.py
      - name: Uninstall minimal Bofire
        run: pip uninstall . -y
      - name: Install Bofire
        run: pip install ".[optimization,tests,cheminfo]"
      - name: Install ipopt
        run: sudo apt install build-essential pkg-config coinor-libipopt1v5 coinor-libipopt-dev
      - name: Install cyipopt
        run: pip install cyipopt
      - name: Run tests
        run: pytest -ra --cov=bofire --cov-report term-missing tests
          
